### ISSUE TITLE
Werewolves mod incompatible

### ISSUE THREAD

**Issue by LLjo** [PolarFox27/JobsMod#9]
Crash during startup. 1.16.5
 
 Exception caught during firing event: class com.polarfox27.jobs.data.JobsInfo cannot be cast to class de.teamlapen.werewolves.player.werewolf.WerewolfPlayer (com.polarfox27.jobs.data.JobsInfo and de.teamlapen.werewolves.player.werewolf.WerewolfPlayer are in unnamed module of loader cpw.mods.modlauncher.TransformingClassLoader @3305897c)
        Index: 5
        Listeners:
                0: NORMAL
                1: ASM: class com.github.alexthe666.alexsmobs.event.ServerEvents onEntityResize(Lnet/minecraftforge/event/entity/EntityEvent$Size;)V
                2: ASM: class com.minecraftabnormals.personality.common.CommonEvents onEvent(Lnet/minecraftforge/event/entity/EntityEvent$Size;)V
                3: ASM: class com.minecraftabnormals.upgrade_aquatic.core.events.EntityEvents onDrownedPoseChange(Lnet/minecraftforge/event/entity/EntityEvent$Size;)V
                4: ASM: class com.simibubi.create.content.contraptions.components.deployer.DeployerFakePlayer deployerHasEyesOnHisFeet(Lnet/minecraftforge/event/entity/EntityEvent$Size;)V
                5: ASM: de.teamlapen.werewolves.player.ModPlayerEventHandler@cdaaabe playerSize(Lnet/minecraftforge/event/entity/EntityEvent$Size;)V
                6: ASM: de.teamlapen.vampirism.player.ModPlayerEventHandler@61311990 eyeHeight(Lnet/minecraftforge/event/entity/EntityEvent$Size;)V
                7: ASM: de.teamlapen.vampirism.entity.ModEntityEventHandler@32447f68 onEyeHeightSet(Lnet/minecraftforge/event/entity/EntityEvent$Size;)V
java.lang.ClassCastException: class com.polarfox27.jobs.data.JobsInfo cannot be cast to class de.teamlapen.werewolves.player.werewolf.WerewolfPlayer (com.polarfox27.jobs.data.JobsInfo and de.teamlapen.werewolves.player.werewolf.WerewolfPlayer are in unnamed module of loader cpw.mods.modlauncher.TransformingClassLoader @3305897c)
        at net.minecraftforge.common.util.LazyOptional.map(LazyOptional.java:210)
        at de.teamlapen.werewolves.player.ModPlayerEventHandler.playerSize(ModPlayerEventHandler.java:210)
        at net.minecraftforge.eventbus.ASMEventHandler_2082_ModPlayerEventHandler_playerSize_Size.invoke(.dynamic)
        at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
        at net.minecraftforge.event.ForgeEventFactory.getEntitySizeForge(ForgeEventFactory.java:781)
        at net.minecraft.entity.Entity.func_213323_x_(Entity.java:2360)
        at de.teamlapen.werewolves.player.werewolf.WerewolfPlayer.switchForm(WerewolfPlayer.java:129)
        at de.teamlapen.werewolves.player.werewolf.WerewolfPlayer.loadData(WerewolfPlayer.java:556)
        at de.teamlapen.werewolves.player.werewolf.WerewolfPlayer$Storage.readNBT(WerewolfPlayer.java:671)
        at de.teamlapen.werewolves.player.werewolf.WerewolfPlayer$Storage.readNBT(WerewolfPlayer.java:660)
        at de.teamlapen.werewolves.player.werewolf.WerewolfPlayer$1.deserializeNBT(WerewolfPlayer.java:643)
        at de.teamlapen.werewolves.player.werewolf.WerewolfPlayer$1.deserializeNBT(WerewolfPlayer.java:625)
        at net.minecraftforge.common.capabilities.CapabilityDispatcher.deserializeNBT(CapabilityDispatcher.java:139)
        at net.minecraftforge.common.capabilities.CapabilityProvider.deserializeCaps(CapabilityProvider.java:96)
        at net.minecraft.entity.Entity.func_70020_e(Entity.java:1483)
        at net.minecraft.world.storage.PlayerData.func_237336_b_(PlayerData.java:56)
        at net.minecraft.server.management.PlayerList.func_72380_a(PlayerList.java:294)
        at net.minecraft.server.management.PlayerList.func_72355_a(PlayerList.java:128)
        at net.minecraft.network.login.ServerLoginNetHandler.func_147326_c(ServerLoginNetHandler.java:118)
        at net.minecraft.network.login.ServerLoginNetHandler.func_73660_a(ServerLoginNetHandler.java:65)
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:222)
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:134)
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:865)
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:291)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787)
        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642)
        at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232)
        at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by LLjo** [comment]
Actually it doesnt crash. It just doesnt let the players join the server

**Comment by PolarFox27** [comment]
Ok, apparently player capabilities aren't compatible with other mods, I'll try to fix that, but it could take a long time
